[package]
name = "file-unpumper"
version = "0.2.0"
edition = "2021"

[dependencies]
goblin = "^0.7"
memmap2 = "^0.7"
rayon = "^1.7"
indicatif = "^0.17"
clap = { version = "^4.3", features = ["derive"] }
